# Generated by Django 4.2.4 on 2023-08-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='midea/cause')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='midea/organizer')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizar.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizar.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acccounts.donater')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizar.cause'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizar.organization'),
        ),
    ]
